name: alhalawa_flutter_boilerplate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Network
  dio: ^5.1.1

  # localization
  easy_localization: ^3.0.1

  # Routing
  go_router: ^7.0.0

  # DI
  get_it: ^7.3.0
  injectable: ^2.1.1

  # Modeling
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0

  # State management
  equatable: ^2.0.3
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  stream_transform: ^2.1.0
  rxdart: ^0.27.7

  # Other
  dartz: ^0.10.1
  intl: ^0.18.0
  tuple: ^2.0.1
  logger: ^1.3.0
  mockito: ^5.4.0
  flutter_dotenv: ^5.0.2
  fpdart: ^0.5.0
  mason: ^0.1.0-dev.49
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  bloc_test: ^9.1.1
  mason_cli: ^0.1.0-dev.50


flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/translations/
#  fonts: